### PR TITLE
BUG: Fixes bug, adds unittest to prevent, adds exception handling, and include CI

### PR DESCRIPTION
**Pull request by linwoodc3**
This is a bug fix to something I unknowingly causes in the merge request a month ago.  The CI piece is trial and error so that's why there are so many.  The code changes are minimal.  More importantly, it fixes a bug likely causes by me and makes it so no one else can break good-morning.

- urllib2 gone and replaced with @petercerno original code
- updated readme; added example of financials class
- created a tests folder with 3 simple unit tests; make sure a break like this doesn't happen again
- Includes exception handling (unit test included)
    - exception for someone entering an empty string
    - exception for someone entering an incorrect ticket symbol
-  Include continuous integration to run unittests anytime some requests a pull requests.  
    - Requires action from @petercerno , but will limit time spent reviewing pull requests
    -  **Action**:  Just add Travis CI and Appveyor to your github.  

To add CI to good-morning it only takes a few clicks: 
1.  Follow instructions here:  https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI
2.  Follow instructions here:  https://www.appveyor.com/docs/#step-1---sign-in-with-appveyor

Travis gives coverage for Linux and OSX; Appveyor gives coverage for Windows.  

Now, when anyone does a pull request, the unit tests launch automatically, and if it doesn't pass, you know the pull request breaks `good-morning`.

### CODE REVIEW

**Comment by linwoodc3** [comment]
Closes #6.  Closes #7

**Comment by petercerno** [comment]
I really appreciate your contribution and your enthusiasm for the project. Unfortunately, I cannot accept your pull request in the current form (as it is a bundle of two independent changes). Would it be possible to create another pull request containing only the bug fix (and nothing else)?

I do not want to add the CI code as it adds unnecessary complexity, i.e. I prefer to keep the code as simple as possible (without any distractions), and the library as small as possible.

**Comment by linwoodc3** [comment]
No unittests either?  That will check to see if the url return has changed or not.

**Comment by linwoodc3** [comment]
And being transparent, the enthusiasm is around the utility of the code.  I can use this library for "Buffett-style" security analysis, so, it helps me. :-)

**Comment by petercerno** [comment]
Ah, sorry, yes it is perfectly fine to add unit tests. Maybe add a small comment about how to run the unit tests (either in README, or the unit tests themselves). Thanks a lot!

**Pull request closed without merging**
